<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Yen Huynh" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="r-markdown" class="section level2">
<h2>R Markdown</h2>
<p>YEN BAO HUYNH ybh83</p>
<p>#HERE IS MY PROJECT
The dataset was acquired from the Exposome Explorer website (<a href="http://exposome-explorer.iarc.fr/" class="uri">http://exposome-explorer.iarc.fr/</a>). This website a database about biomarkers of exposure to environmental risk factors for diseases. From this site, I got a cancer associations dataset. This datatset is about the different acquired specimens of cancer patients. The dataset, generally, provides information such as what biomarkers were used to identify the different cancers, what kind of analytical method (GC-MS, LC-MS, HPLC, etc) were used, and some other related epidemiological data.</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.3     ✓ purrr   0.3.4
## ✓ tibble  3.0.4     ✓ dplyr   1.0.2
## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
## ✓ readr   1.4.0     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(dplyr)</code></pre>
<pre class="r"><code>cancer_dat &lt;-read_csv(&quot;cancer_association_forR.csv&quot;)</code></pre>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   ID = col_double(),
##   ExcretionID = col_double(),
##   Subjectgroup = col_character(),
##   Population = col_character(),
##   Country = col_character(),
##   Cohort = col_character(),
##   Number_of_subjects = col_double(),
##   Number_of_cases = col_double(),
##   Numberofcontrols = col_double(),
##   Biospecimen = col_character(),
##   analytical_method = col_character(),
##   Biomarker = col_character(),
##   Biomarker_detail = col_character(),
##   Cancer = col_character(),
##   Study_design = col_character(),
##   Publication = col_character()
## )</code></pre>
<pre class="r"><code>glimpse(cancer_dat)</code></pre>
<pre><code>## Rows: 1,356
## Columns: 16
## $ ID                 &lt;dbl&gt; 1, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 36, 37, 38,…
## $ ExcretionID        &lt;dbl&gt; 20999, 21004, 21005, 21006, 21007, 21008, 21009, 2…
## $ Subjectgroup       &lt;chr&gt; &quot;All&quot;, &quot;All&quot;, &quot;All&quot;, &quot;All&quot;, &quot;All&quot;, &quot;All&quot;, &quot;All&quot;, &quot;…
## $ Population         &lt;chr&gt; &quot;Renal cell carcinoma cases and their controls&quot;, &quot;…
## $ Country            &lt;chr&gt; &quot;Finland&quot;, &quot;Netherlands&quot;, &quot;Netherlands&quot;, &quot;Netherla…
## $ Cohort             &lt;chr&gt; &quot;ATBC (Alpha-Tocopherol, Beta-Carotene Cancer Prev…
## $ Number_of_subjects &lt;dbl&gt; 448, 3004, 3004, 3004, 3004, 3004, 3004, 3004, 300…
## $ Number_of_cases    &lt;dbl&gt; 224, 1502, 1502, 1502, 1502, 1502, 1502, 1502, 150…
## $ Numberofcontrols   &lt;dbl&gt; 224, 1502, 1502, 1502, 1502, 1502, 1502, 1502, 150…
## $ Biospecimen        &lt;chr&gt; &quot;Serum, fasting&quot;, &quot;Plasma, fasting and non-fasting…
## $ analytical_method  &lt;chr&gt; &quot;Competitive protein-binding assay (CPBA)&quot;, &quot;HPLC&quot;…
## $ Biomarker          &lt;chr&gt; &quot;Folates&quot;, &quot;alpha-Carotene&quot;, &quot;beta-Carotene&quot;, &quot;Lyc…
## $ Biomarker_detail   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ Cancer             &lt;chr&gt; &quot;Kidney cancer&quot;, &quot;Breast cancer&quot;, &quot;Breast cancer&quot;,…
## $ Study_design       &lt;chr&gt; &quot;Nested case-control study&quot;, &quot;Nested case-control …
## $ Publication        &lt;chr&gt; &quot;Gibson 2010&quot;, &quot;Bakker 2016&quot;, &quot;Bakker 2016&quot;, &quot;Bakk…</code></pre>
<p>#How many observations in the original dataset?</p>
<pre class="r"><code>count(cancer_dat)</code></pre>
<pre><code>## # A tibble: 1 x 1
##       n
##   &lt;int&gt;
## 1  1356</code></pre>
<pre class="r"><code>#Answer: 1356 observations</code></pre>
<p>#Just doing some tidying here. I’m only interested in biological samples that were analyzed by either HPLC or LC-MS/MS so I filtered out those two data. Also by this way I can create binary variables for this project…</p>
<pre class="r"><code>cancer_dat2 &lt;- cancer_dat%&gt;%select(-&quot;Biomarker_detail&quot;)%&gt;%na.omit()%&gt;%filter(analytical_method==&quot;HPLC&quot;)
cancer_dat3 &lt;- cancer_dat%&gt;%select(-&quot;Biomarker_detail&quot;)%&gt;%na.omit()%&gt;%filter(analytical_method==&quot;LC-MS/MS&quot;)
cancerdata&lt;-rbind(cancer_dat3,cancer_dat2)
cancerdata_final&lt;-cancerdata%&gt;%mutate(y=ifelse(analytical_method==&quot;LC-MS/MS&quot;,1,0))</code></pre>
<p><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss some of the MANOVA assumptions and whether or not they are likely to have been met here (no need for anything too in-depth) (2).
<strong>1. (15 pts)</strong> Let’s see if the No. of subjects and No.of cases are different among cancers (the different types of cancers)</p>
<pre class="r"><code>#Firstly, test with MANOVA
man1 &lt;- manova(cbind(Number_of_subjects,Number_of_cases)~Cancer, data=cancerdata_final)

summary(man1)</code></pre>
<pre><code>##            Df  Pillai approx F num Df den Df    Pr(&gt;F)    
## Cancer     14 0.19237   4.3633     28   1148 6.472e-13 ***
## Residuals 574                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#p-value is much lower than 0.05. Overall MANOVA is significant</code></pre>
<pre class="r"><code>#The difference is significant now. Let&#39;s do ANOVA to see which is different across the cancer types: number of subjects or number of cases
summary.aov(man1)</code></pre>
<pre><code>##  Response Number_of_subjects :
##              Df    Sum Sq Mean Sq F value    Pr(&gt;F)    
## Cancer       14 125697886 8978420  5.9996 3.985e-11 ***
## Residuals   574 858991240 1496500                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response Number_of_cases :
##              Df    Sum Sq Mean Sq F value    Pr(&gt;F)    
## Cancer       14  22683245 1620232   5.561 3.991e-10 ***
## Residuals   574 167239534  291358                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#Seems like both the number of subjects and number of cases are significantly different across the different types of cancer.  So, at least one type of cancer differs!</code></pre>
<pre class="r"><code>#Post-hoc t tests
cancerdata_final%&gt;%group_by(Cancer)%&gt;%summarize(mean(Number_of_subjects),mean(Number_of_cases))</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 15 x 3
##    Cancer                       `mean(Number_of_subjects… `mean(Number_of_cases…
##    &lt;chr&gt;                                            &lt;dbl&gt;                  &lt;dbl&gt;
##  1 Bladder cancer                                    499.                  235. 
##  2 Brain cancer                                      128                    64  
##  3 Breast cancer                                    1358.                  598. 
##  4 Cervical cancer                                   146.                   48.9
##  5 Colon and rectal cancer                          1748.                  718. 
##  6 Gastric and oesophageal can…                     1330.                  402. 
##  7 Head and neck cancer                              220.                   75.1
##  8 Kidney cancer                                     780                   390  
##  9 Liver cancer                                     1070.                  199  
## 10 Lung cancer                                      1306.                  510. 
## 11 Lymphoid cancer                                   809                   271  
## 12 Ovarian cancer                                    102                    35  
## 13 Pancreatic cancer                                 670.                  315. 
## 14 Prostate cancer                                  1409.                  534. 
## 15 Skin cancer                                       236.                   90.9</code></pre>
<pre class="r"><code>pairwise.t.test(cancerdata_final$Number_of_subjects,cancerdata_final$Cancer, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  cancerdata_final$Number_of_subjects and cancerdata_final$Cancer 
## 
##                                Bladder cancer Brain cancer Breast cancer
## Brain cancer                   0.33973        -            -            
## Breast cancer                  0.00020        0.00032      -            
## Cervical cancer                0.42231        0.97198      0.00242      
## Colon and rectal cancer        6.4e-06        1.5e-05      0.05073      
## Gastric and oesophageal cancer 0.00154        0.00096      0.87756      
## Head and neck cancer           0.38612        0.82252      1.6e-05      
## Kidney cancer                  0.66425        0.34757      0.35080      
## Liver cancer                   0.10994        0.03110      0.34262      
## Lung cancer                    0.00483        0.00202      0.81113      
## Lymphoid cancer                0.43767        0.14892      0.11927      
## Ovarian cancer                 0.38679        0.96034      0.00279      
## Pancreatic cancer              0.63153        0.21402      0.02357      
## Prostate cancer                0.00019        0.00026      0.73538      
## Skin cancer                    0.46851        0.80756      0.00033      
##                                Cervical cancer Colon and rectal cancer
## Brain cancer                   -               -                      
## Breast cancer                  -               -                      
## Cervical cancer                -               -                      
## Colon and rectal cancer        0.00018         -                      
## Gastric and oesophageal cancer 0.00467         0.07598                
## Head and neck cancer           0.87190         5.5e-07                
## Kidney cancer                  0.38123         0.12898                
## Liver cancer                   0.05591         0.04545                
## Lung cancer                    0.00750         0.09238                
## Lymphoid cancer                0.19796         0.01439                
## Ovarian cancer                 0.93791         0.00023                
## Pancreatic cancer              0.27747         0.00151                
## Prostate cancer                0.00192         0.11424                
## Skin cancer                    0.85394         1.4e-05                
##                                Gastric and oesophageal cancer
## Brain cancer                   -                             
## Breast cancer                  -                             
## Cervical cancer                -                             
## Colon and rectal cancer        -                             
## Gastric and oesophageal cancer -                             
## Head and neck cancer           0.00014                       
## Kidney cancer                  0.38402                       
## Liver cancer                   0.42810                       
## Lung cancer                    0.92492                       
## Lymphoid cancer                0.16337                       
## Ovarian cancer                 0.00507                       
## Pancreatic cancer              0.04452                       
## Prostate cancer                0.68708                       
## Skin cancer                    0.00115                       
##                                Head and neck cancer Kidney cancer Liver cancer
## Brain cancer                   -                    -             -           
## Breast cancer                  -                    -             -           
## Cervical cancer                -                    -             -           
## Colon and rectal cancer        -                    -             -           
## Gastric and oesophageal cancer -                    -             -           
## Head and neck cancer           -                    -             -           
## Kidney cancer                  0.39534              -             -           
## Liver cancer                   0.02490              0.66813       -           
## Lung cancer                    0.00053              0.41224       0.49633     
## Lymphoid cancer                0.15939              0.96694       0.55790     
## Ovarian cancer                 0.80470              0.35676       0.05307     
## Pancreatic cancer              0.23388              0.87116       0.32730     
## Prostate cancer                1.6e-05              0.31337       0.27866     
## Skin cancer                    0.96693              0.42357       0.04416     
##                                Lung cancer Lymphoid cancer Ovarian cancer
## Brain cancer                   -           -               -             
## Breast cancer                  -           -               -             
## Cervical cancer                -           -               -             
## Colon and rectal cancer        -           -               -             
## Gastric and oesophageal cancer -           -               -             
## Head and neck cancer           -           -               -             
## Kidney cancer                  -           -               -             
## Liver cancer                   -           -               -             
## Lung cancer                    -           -               -             
## Lymphoid cancer                0.20332     -               -             
## Ovarian cancer                 0.00783     0.18313         -             
## Pancreatic cancer              0.06745     0.75549         0.25564       
## Prostate cancer                0.65260     0.09626         0.00222       
## Skin cancer                    0.00261     0.20381         0.79118       
##                                Pancreatic cancer Prostate cancer
## Brain cancer                   -                 -              
## Breast cancer                  -                 -              
## Cervical cancer                -                 -              
## Colon and rectal cancer        -                 -              
## Gastric and oesophageal cancer -                 -              
## Head and neck cancer           -                 -              
## Kidney cancer                  -                 -              
## Liver cancer                   -                 -              
## Lung cancer                    -                 -              
## Lymphoid cancer                -                 -              
## Ovarian cancer                 -                 -              
## Pancreatic cancer              -                 -              
## Prostate cancer                0.01848           -              
## Skin cancer                    0.29385           0.00027        
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(cancerdata_final$Number_of_cases,cancerdata_final$Cancer, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  cancerdata_final$Number_of_cases and cancerdata_final$Cancer 
## 
##                                Bladder cancer Brain cancer Breast cancer
## Brain cancer                   0.32005        -            -            
## Breast cancer                  0.00036        0.00040      -            
## Cervical cancer                0.33933        0.94616      0.00186      
## Colon and rectal cancer        7.3e-05        7.5e-05      0.17104      
## Gastric and oesophageal cancer 0.14578        0.03456      0.01469      
## Head and neck cancer           0.26249        0.95099      7.3e-06      
## Kidney cancer                  0.58618        0.28720      0.44722      
## Liver cancer                   0.82114        0.48306      0.00297      
## Lung cancer                    0.02907        0.00800      0.35521      
## Lymphoid cancer                0.83619        0.31984      0.03574      
## Ovarian cancer                 0.32436        0.89997      0.00240      
## Pancreatic cancer              0.60802        0.19185      0.03506      
## Prostate cancer                0.00529        0.00236      0.34310      
## Skin cancer                    0.37048        0.89029      0.00024      
##                                Cervical cancer Colon and rectal cancer
## Brain cancer                   -               -                      
## Breast cancer                  -               -                      
## Cervical cancer                -               -                      
## Colon and rectal cancer        0.00039         -                      
## Gastric and oesophageal cancer 0.05515         0.00245                
## Head and neck cancer           0.89691         1.8e-06                
## Kidney cancer                  0.28590         0.24323                
## Liver cancer                   0.48106         0.00054                
## Lung cancer                    0.01598         0.07230                
## Lymphoid cancer                0.32837         0.00828                
## Ovarian cancer                 0.95532         0.00053                
## Pancreatic cancer              0.21126         0.00714                
## Prostate cancer                0.00691         0.05153                
## Skin cancer                    0.84533         4.4e-05                
##                                Gastric and oesophageal cancer
## Brain cancer                   -                             
## Breast cancer                  -                             
## Cervical cancer                -                             
## Colon and rectal cancer        -                             
## Gastric and oesophageal cancer -                             
## Head and neck cancer           0.01074                       
## Kidney cancer                  0.96458                       
## Liver cancer                   0.15990                       
## Lung cancer                    0.32559                       
## Lymphoid cancer                0.42529                       
## Ovarian cancer                 0.05689                       
## Pancreatic cancer              0.54724                       
## Prostate cancer                0.13107                       
## Skin cancer                    0.03548                       
##                                Head and neck cancer Kidney cancer Liver cancer
## Brain cancer                   -                    -             -           
## Breast cancer                  -                    -             -           
## Cervical cancer                -                    -             -           
## Colon and rectal cancer        -                    -             -           
## Gastric and oesophageal cancer -                    -             -           
## Head and neck cancer           -                    -             -           
## Kidney cancer                  0.27909              -             -           
## Liver cancer                   0.45798              0.52234       -           
## Lung cancer                    0.00166              0.67158       0.04277     
## Lymphoid cancer                0.28891              0.69995       0.71414     
## Ovarian cancer                 0.84858              0.27422       0.45704     
## Pancreatic cancer              0.15044              0.80249       0.51817     
## Prostate cancer                0.00016              0.60140       0.01557     
## Skin cancer                    0.92583              0.31910       0.55391     
##                                Lung cancer Lymphoid cancer Ovarian cancer
## Brain cancer                   -           -               -             
## Breast cancer                  -           -               -             
## Cervical cancer                -           -               -             
## Colon and rectal cancer        -           -               -             
## Gastric and oesophageal cancer -           -               -             
## Head and neck cancer           -           -               -             
## Kidney cancer                  -           -               -             
## Liver cancer                   -           -               -             
## Lung cancer                    -           -               -             
## Lymphoid cancer                0.16588     -               -             
## Ovarian cancer                 0.01737     0.31375         -             
## Pancreatic cancer              0.20419     0.82155         0.20384       
## Prostate cancer                0.81380     0.09882         0.00809       
## Skin cancer                    0.00752     0.36548         0.80179       
##                                Pancreatic cancer Prostate cancer
## Brain cancer                   -                 -              
## Breast cancer                  -                 -              
## Cervical cancer                -                 -              
## Colon and rectal cancer        -                 -              
## Gastric and oesophageal cancer -                 -              
## Head and neck cancer           -                 -              
## Kidney cancer                  -                 -              
## Liver cancer                   -                 -              
## Lung cancer                    -                 -              
## Lymphoid cancer                -                 -              
## Ovarian cancer                 -                 -              
## Pancreatic cancer              -                 -              
## Prostate cancer                0.11394           -              
## Skin cancer                    0.21938           0.00182        
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#Answer: only a few types of cancer are significantly different from each other in terms of number of subjects and number of cases studied. For example: Brain cancer vs Colon and rectal cancer, brain cancer vs lung cancer, breast cancer vs lung cancer, colon and rectal cancer vs lung cancer, etc (p-value&lt; 0.05 are showed in the result). Those with no reported p-value could be because there are two few observations for that specific cancer group. </code></pre>
<pre class="r"><code>#So i conducted 1 Manova, 2 Anovas,  90 t-tests. Overall, I did 103 tests in total. #bonferroni α 
0.05/103</code></pre>
<pre><code>## [1] 0.0004854369</code></pre>
<pre class="r"><code>1-0.05^103</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>#If I want to keep the overall type I error rate at .05, I should be using 0.0004854369 as the boneferonni adjusted rate. </code></pre>
<pre class="r"><code>#Adjusting for multiple comparison using bonferroni correction
cancerdata_final%&gt;%group_by(Cancer)%&gt;%summarize(mean(Number_of_subjects),mean(Number_of_cases))</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 15 x 3
##    Cancer                       `mean(Number_of_subjects… `mean(Number_of_cases…
##    &lt;chr&gt;                                            &lt;dbl&gt;                  &lt;dbl&gt;
##  1 Bladder cancer                                    499.                  235. 
##  2 Brain cancer                                      128                    64  
##  3 Breast cancer                                    1358.                  598. 
##  4 Cervical cancer                                   146.                   48.9
##  5 Colon and rectal cancer                          1748.                  718. 
##  6 Gastric and oesophageal can…                     1330.                  402. 
##  7 Head and neck cancer                              220.                   75.1
##  8 Kidney cancer                                     780                   390  
##  9 Liver cancer                                     1070.                  199  
## 10 Lung cancer                                      1306.                  510. 
## 11 Lymphoid cancer                                   809                   271  
## 12 Ovarian cancer                                    102                    35  
## 13 Pancreatic cancer                                 670.                  315. 
## 14 Prostate cancer                                  1409.                  534. 
## 15 Skin cancer                                       236.                   90.9</code></pre>
<pre class="r"><code>pairwise.t.test(cancerdata_final$Number_of_subjects,cancerdata_final$Cancer, p.adj=&quot;bonferroni&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  cancerdata_final$Number_of_subjects and cancerdata_final$Cancer 
## 
##                                Bladder cancer Brain cancer Breast cancer
## Brain cancer                   1.00000        -            -            
## Breast cancer                  0.02090        0.03379      -            
## Cervical cancer                1.00000        1.00000      0.25400      
## Colon and rectal cancer        0.00068        0.00162      1.00000      
## Gastric and oesophageal cancer 0.16204        0.10050      1.00000      
## Head and neck cancer           1.00000        1.00000      0.00168      
## Kidney cancer                  1.00000        1.00000      1.00000      
## Liver cancer                   1.00000        1.00000      1.00000      
## Lung cancer                    0.50767        0.21170      1.00000      
## Lymphoid cancer                1.00000        1.00000      1.00000      
## Ovarian cancer                 1.00000        1.00000      0.29287      
## Pancreatic cancer              1.00000        1.00000      1.00000      
## Prostate cancer                0.01994        0.02736      1.00000      
## Skin cancer                    1.00000        1.00000      0.03489      
##                                Cervical cancer Colon and rectal cancer
## Brain cancer                   -               -                      
## Breast cancer                  -               -                      
## Cervical cancer                -               -                      
## Colon and rectal cancer        0.01910         -                      
## Gastric and oesophageal cancer 0.49028         1.00000                
## Head and neck cancer           1.00000         5.8e-05                
## Kidney cancer                  1.00000         1.00000                
## Liver cancer                   1.00000         1.00000                
## Lung cancer                    0.78723         1.00000                
## Lymphoid cancer                1.00000         1.00000                
## Ovarian cancer                 1.00000         0.02444                
## Pancreatic cancer              1.00000         0.15904                
## Prostate cancer                0.20167         1.00000                
## Skin cancer                    1.00000         0.00148                
##                                Gastric and oesophageal cancer
## Brain cancer                   -                             
## Breast cancer                  -                             
## Cervical cancer                -                             
## Colon and rectal cancer        -                             
## Gastric and oesophageal cancer -                             
## Head and neck cancer           0.01491                       
## Kidney cancer                  1.00000                       
## Liver cancer                   1.00000                       
## Lung cancer                    1.00000                       
## Lymphoid cancer                1.00000                       
## Ovarian cancer                 0.53190                       
## Pancreatic cancer              1.00000                       
## Prostate cancer                1.00000                       
## Skin cancer                    0.12089                       
##                                Head and neck cancer Kidney cancer Liver cancer
## Brain cancer                   -                    -             -           
## Breast cancer                  -                    -             -           
## Cervical cancer                -                    -             -           
## Colon and rectal cancer        -                    -             -           
## Gastric and oesophageal cancer -                    -             -           
## Head and neck cancer           -                    -             -           
## Kidney cancer                  1.00000              -             -           
## Liver cancer                   1.00000              1.00000       -           
## Lung cancer                    0.05572              1.00000       1.00000     
## Lymphoid cancer                1.00000              1.00000       1.00000     
## Ovarian cancer                 1.00000              1.00000       1.00000     
## Pancreatic cancer              1.00000              1.00000       1.00000     
## Prostate cancer                0.00164              1.00000       1.00000     
## Skin cancer                    1.00000              1.00000       1.00000     
##                                Lung cancer Lymphoid cancer Ovarian cancer
## Brain cancer                   -           -               -             
## Breast cancer                  -           -               -             
## Cervical cancer                -           -               -             
## Colon and rectal cancer        -           -               -             
## Gastric and oesophageal cancer -           -               -             
## Head and neck cancer           -           -               -             
## Kidney cancer                  -           -               -             
## Liver cancer                   -           -               -             
## Lung cancer                    -           -               -             
## Lymphoid cancer                1.00000     -               -             
## Ovarian cancer                 0.82235     1.00000         -             
## Pancreatic cancer              1.00000     1.00000         1.00000       
## Prostate cancer                1.00000     1.00000         0.23309       
## Skin cancer                    0.27419     1.00000         1.00000       
##                                Pancreatic cancer Prostate cancer
## Brain cancer                   -                 -              
## Breast cancer                  -                 -              
## Cervical cancer                -                 -              
## Colon and rectal cancer        -                 -              
## Gastric and oesophageal cancer -                 -              
## Head and neck cancer           -                 -              
## Kidney cancer                  -                 -              
## Liver cancer                   -                 -              
## Lung cancer                    -                 -              
## Lymphoid cancer                -                 -              
## Ovarian cancer                 -                 -              
## Pancreatic cancer              -                 -              
## Prostate cancer                1.00000           -              
## Skin cancer                    1.00000           0.02869        
## 
## P value adjustment method: bonferroni</code></pre>
<pre class="r"><code>pairwise.t.test(cancerdata_final$Number_of_cases,cancerdata_final$Cancer, p.adj=&quot;bonferroni&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  cancerdata_final$Number_of_cases and cancerdata_final$Cancer 
## 
##                                Bladder cancer Brain cancer Breast cancer
## Brain cancer                   1.00000        -            -            
## Breast cancer                  0.03792        0.04228      -            
## Cervical cancer                1.00000        1.00000      0.19514      
## Colon and rectal cancer        0.00763        0.00784      1.00000      
## Gastric and oesophageal cancer 1.00000        1.00000      1.00000      
## Head and neck cancer           1.00000        1.00000      0.00076      
## Kidney cancer                  1.00000        1.00000      1.00000      
## Liver cancer                   1.00000        1.00000      0.31207      
## Lung cancer                    1.00000        0.84023      1.00000      
## Lymphoid cancer                1.00000        1.00000      1.00000      
## Ovarian cancer                 1.00000        1.00000      0.25182      
## Pancreatic cancer              1.00000        1.00000      1.00000      
## Prostate cancer                0.55592        0.24827      1.00000      
## Skin cancer                    1.00000        1.00000      0.02527      
##                                Cervical cancer Colon and rectal cancer
## Brain cancer                   -               -                      
## Breast cancer                  -               -                      
## Cervical cancer                -               -                      
## Colon and rectal cancer        0.04111         -                      
## Gastric and oesophageal cancer 1.00000         0.25730                
## Head and neck cancer           1.00000         0.00018                
## Kidney cancer                  1.00000         1.00000                
## Liver cancer                   1.00000         0.05668                
## Lung cancer                    1.00000         1.00000                
## Lymphoid cancer                1.00000         0.86975                
## Ovarian cancer                 1.00000         0.05578                
## Pancreatic cancer              1.00000         0.74939                
## Prostate cancer                0.72538         1.00000                
## Skin cancer                    1.00000         0.00461                
##                                Gastric and oesophageal cancer
## Brain cancer                   -                             
## Breast cancer                  -                             
## Cervical cancer                -                             
## Colon and rectal cancer        -                             
## Gastric and oesophageal cancer -                             
## Head and neck cancer           1.00000                       
## Kidney cancer                  1.00000                       
## Liver cancer                   1.00000                       
## Lung cancer                    1.00000                       
## Lymphoid cancer                1.00000                       
## Ovarian cancer                 1.00000                       
## Pancreatic cancer              1.00000                       
## Prostate cancer                1.00000                       
## Skin cancer                    1.00000                       
##                                Head and neck cancer Kidney cancer Liver cancer
## Brain cancer                   -                    -             -           
## Breast cancer                  -                    -             -           
## Cervical cancer                -                    -             -           
## Colon and rectal cancer        -                    -             -           
## Gastric and oesophageal cancer -                    -             -           
## Head and neck cancer           -                    -             -           
## Kidney cancer                  1.00000              -             -           
## Liver cancer                   1.00000              1.00000       -           
## Lung cancer                    0.17384              1.00000       1.00000     
## Lymphoid cancer                1.00000              1.00000       1.00000     
## Ovarian cancer                 1.00000              1.00000       1.00000     
## Pancreatic cancer              1.00000              1.00000       1.00000     
## Prostate cancer                0.01629              1.00000       1.00000     
## Skin cancer                    1.00000              1.00000       1.00000     
##                                Lung cancer Lymphoid cancer Ovarian cancer
## Brain cancer                   -           -               -             
## Breast cancer                  -           -               -             
## Cervical cancer                -           -               -             
## Colon and rectal cancer        -           -               -             
## Gastric and oesophageal cancer -           -               -             
## Head and neck cancer           -           -               -             
## Kidney cancer                  -           -               -             
## Liver cancer                   -           -               -             
## Lung cancer                    -           -               -             
## Lymphoid cancer                1.00000     -               -             
## Ovarian cancer                 1.00000     1.00000         -             
## Pancreatic cancer              1.00000     1.00000         1.00000       
## Prostate cancer                1.00000     1.00000         0.84956       
## Skin cancer                    0.78971     1.00000         1.00000       
##                                Pancreatic cancer Prostate cancer
## Brain cancer                   -                 -              
## Breast cancer                  -                 -              
## Cervical cancer                -                 -              
## Colon and rectal cancer        -                 -              
## Gastric and oesophageal cancer -                 -              
## Head and neck cancer           -                 -              
## Kidney cancer                  -                 -              
## Liver cancer                   -                 -              
## Lung cancer                    -                 -              
## Lymphoid cancer                -                 -              
## Ovarian cancer                 -                 -              
## Pancreatic cancer              -                 -              
## Prostate cancer                1.00000           -              
## Skin cancer                    1.00000           0.19139        
## 
## P value adjustment method: bonferroni</code></pre>
<pre class="r"><code>#Results now show that only head and neck is siggnificantly different from prostate cancer, in terms of number of subjects and number of cases studied.</code></pre>
<pre class="r"><code>#Discussing some MANOVA assumptions:
library(rstatix)</code></pre>
<pre><code>## 
## Attaching package: &#39;rstatix&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<pre class="r"><code>group &lt;- cancerdata_final$Cancer
DVs &lt;- cancerdata_final %&gt;% select(Number_of_subjects,Number_of_cases)
#Test homogeneity of (co)variances
box_m(DVs, group)</code></pre>
<pre><code>## Warning in log(unlist(lapply(mats, det))): NaNs produced</code></pre>
<pre><code>## # A tibble: 1 x 4
##   statistic p.value parameter method                                            
##       &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;                                             
## 1       NaN     NaN        42 Box&#39;s M-test for Homogeneity of Covariance Matric…</code></pre>
<pre class="r"><code>#*Answers: this assumption was not met. Could it be because I have too few observations for some cancer types?</code></pre>
<p><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</p>
<pre class="r"><code>#Question: is there an association between the mean number of subjects study and the country?
#Null hypothesis H0: the mean number of subjects studied is the same across different countries
#HA: the mean number of subjects studied is different across different countries</code></pre>
<pre class="r"><code>cancerdata_final%&gt;%count(analytical_method)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   analytical_method     n
##   &lt;chr&gt;             &lt;int&gt;
## 1 HPLC                513
## 2 LC-MS/MS             76</code></pre>
<pre class="r"><code>ran_dist_dat&lt;-cancerdata_final%&gt;%select(analytical_method, Number_of_subjects)%&gt;%group_by(analytical_method)%&gt;%glimpse()</code></pre>
<pre><code>## Rows: 589
## Columns: 2
## Groups: analytical_method [2]
## $ analytical_method  &lt;chr&gt; &quot;LC-MS/MS&quot;, &quot;LC-MS/MS&quot;, &quot;LC-MS/MS&quot;, &quot;LC-MS/MS&quot;, &quot;L…
## $ Number_of_subjects &lt;dbl&gt; 928, 1412, 927, 2669, 2669, 836, 836, 836, 928, 18…</code></pre>
<pre class="r"><code>#look at the distribution of the number of subjects in each country. 
ggplot(ran_dist_dat,aes(Number_of_subjects,fill=analytical_method))+geom_histogram(bins=6.5)+
  facet_wrap(~analytical_method,ncol=2)+theme(legend.position=&quot;none&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>#observed difference in means of number of subjects across countries
ran_dist_dat%&gt;%group_by(analytical_method)%&gt;%summarize(means=mean(Number_of_subjects))%&gt;%summarize(`mean_diff`=diff(means))</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1      309.</code></pre>
<pre class="r"><code>#accurately simulate the distribution of the mean difference under the null hypothesis
rand_dist&lt;-vector() #create vector to hold diffs under null hypothesis

for(i in 1:5000){
  new&lt;-data.frame(Number_of_subjects=sample(ran_dist_dat$Number_of_subjects),analytical_method=ran_dist_dat$analytical_method) #scramble columns
rand_dist[i]&lt;-mean(new[new$analytical_method==&quot;LC-MS/MS&quot;,]$Number_of_subjects)-   
              mean(new[new$analytical_method==&quot;HPLC&quot;,]$Number_of_subjects)} 

{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = c(-309.1101, 309.1101),col=&quot;red&quot;)}</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<pre class="r"><code>#The p-value comes out to be 0.0504. Close! But we still fail to reject H0.
mean(rand_dist&gt;309.1101 | rand_dist&lt; -309.1101) #two-tailed p value</code></pre>
<pre><code>## [1] 0.0518</code></pre>
<p>#ANSWER: I did a randomization test to test the mean difference between the number of subjects of HPLC method and that of LC-MS/MS method. The final p-value turned out to be 0.0504 (so close to 0.05). I failed to reject the null hypothesis. The mean number of subjects of LC-MS/MS and HPLC is the same.</p>
<p><strong>3. (40 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<pre><code>- Interpret the coefficient estimates (do not discuss significance) (10)
- Plot the regression using `ggplot()` using geom_smooth(method=&quot;lm&quot;). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the `interactions` package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (10)
- What proportion of the variation in the outcome does your model explain? (4)</code></pre>
<pre class="r"><code>cancerdata_final%&gt;%ggplot(aes(Number_of_subjects,Number_of_cases))+geom_point()</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>#regress No.of subjects on No. of cases alone

fit&lt;-lm(Number_of_subjects~Number_of_cases, data= cancerdata_final)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Number_of_subjects ~ Number_of_cases, data = cancerdata_final)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -803.3 -241.1 -147.3   92.1 7230.3 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     240.36854   32.32256   7.437 3.68e-13 ***
## Number_of_cases   2.00516    0.04453  45.028  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 613.7 on 587 degrees of freedom
## Multiple R-squared:  0.7755, Adjusted R-squared:  0.7751 
## F-statistic:  2028 on 1 and 587 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>cancerdata_final%&gt;%ggplot(aes(Number_of_subjects,Number_of_cases))+geom_point()+geom_smooth(method = &#39;lm&#39;,se=F)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
<pre class="r"><code>#Based on the co-efficients, the best-fitting line is 
#Number_of_subjects= 240.36854  + 2.00516 * Number_of_cases


#What proportion of the variation in the outcome does your model explain?
summary(fit)$r.sq</code></pre>
<pre><code>## [1] 0.7754863</code></pre>
<pre class="r"><code>#Answer: 77.54% (Low!)</code></pre>
<pre class="r"><code>#regress No.of subjects on No. of cases alone

fit2&lt;-lm(Number_of_subjects~Numberofcontrols, data= cancerdata_final)
summary(fit2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Number_of_subjects ~ Numberofcontrols, data = cancerdata_final)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3450.6  -126.7   -96.5   128.8  2753.4 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      130.91384   22.28348   5.875 7.09e-09 ***
## Numberofcontrols   1.46227    0.02048  71.400  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 416.2 on 587 degrees of freedom
## Multiple R-squared:  0.8967, Adjusted R-squared:  0.8966 
## F-statistic:  5098 on 1 and 587 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>cancerdata_final%&gt;%ggplot(aes(Number_of_subjects,Numberofcontrols))+geom_point()+geom_smooth(method = &#39;lm&#39;,se=F)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre class="r"><code>#Based on the co-efficients, the best-fitting line is 
#Number_of_subjects= 130.91384   + 1.46227    * Numberofcontrols

#What proportion of the variation in the outcome does your model explain?
summary(fit2)$r.sq</code></pre>
<pre><code>## [1] 0.8967454</code></pre>
<pre class="r"><code>#Answer: 89.67% *still low*</code></pre>
<pre class="r"><code>#regress Number of subjects on Number of cases and Number of controls together


cancerdata_final$center_cases &lt;- cancerdata_final$Number_of_cases - mean(cancerdata_final$Number_of_cases)

cancerdata_final$center_controls &lt;- cancerdata_final$Numberofcontrols - mean(cancerdata_final$Numberofcontrols)

fit3&lt;-lm(Number_of_subjects ~ center_cases*center_controls, data=cancerdata_final)
summary(fit3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Number_of_subjects ~ center_cases * center_controls, 
##     data = cancerdata_final)
## 
## Residuals:
##        Min         1Q     Median         3Q        Max 
## -9.285e-11  3.000e-14  1.110e-13  1.710e-13  2.071e-11 
## 
## Coefficients:
##                               Estimate Std. Error   t value Pr(&gt;|t|)    
## (Intercept)                  1.147e+03  1.702e-13 6.738e+15   &lt;2e-16 ***
## center_cases                 1.000e+00  5.269e-16 1.898e+15   &lt;2e-16 ***
## center_controls              1.000e+00  2.655e-16 3.767e+15   &lt;2e-16 ***
## center_cases:center_controls 3.367e-20  1.578e-19 2.130e-01    0.831    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.94e-12 on 585 degrees of freedom
## Multiple R-squared:      1,  Adjusted R-squared:      1 
## F-statistic: 2.114e+31 on 3 and 585 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#What proportion of the variation in the outcome does your model explain?
summary(fit3)$r.sq</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>#Answer: 100%???</code></pre>
<p>#ANSWER: All values are now centered. The predicted value of number of subjects when the numbers of cases and controls are 0 is ~1147. The coefficient for Number_of_cases is ~1, which is the slope of Number_of_cases on number of subjects while the number of controls is constant. This positive number means that the relationship between number of subjects and number of cases is “visible”. The coefficient for number of controls is also ~1, which is the slope of number of controls on number of subjects while the cases is constant. So it is kinda the same intepretation for the two variables. The coefficient for Number_of_cases:Numberofcontrols is ~0 . It means there is really no difference in slope between number of cases and controls. This variable explains whether there is an interaction between number of cases and number of controls</p>
<p>#Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (5)</p>
<pre class="r"><code>#Normality test. the p-value is &lt;0.05 --&gt; not normal. Null hypothesis is rejected
resids&lt;-lm(Number_of_subjects~Number_of_cases, data=cancerdata_final)$residuals
ks.test(resids, &quot;pnorm&quot;, mean=0, sd(resids))</code></pre>
<pre><code>## Warning in ks.test(resids, &quot;pnorm&quot;, mean = 0, sd(resids)): ties should not be
## present for the Kolmogorov-Smirnov test</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.32422, p-value &lt; 2.2e-16
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code>#linearity and homoskedasticity: not met. non linear and not homoskedastic
fitted&lt;-lm(Number_of_subjects~Number_of_cases, data=cancerdata_final)$fitted.values
resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>#Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (10)</p>
<pre class="r"><code>library(sandwich); library(lmtest)</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>fit5&lt;-lm(Number_of_subjects~Number_of_cases, data=cancerdata_final)
coeftest(fit5, vcov = vcovHC(fit5))</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##                   Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)     240.368544  32.149699  7.4765 2.791e-13 ***
## Number_of_cases   2.005156   0.032425 61.8391 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>fit6&lt;-lm(Number_of_subjects~Numberofcontrols, data=cancerdata_final)
coeftest(fit6, vcov = vcovHC(fit6))</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      130.91384   74.50762  1.7571  0.07943 .  
## Numberofcontrols   1.46227    0.12754 11.4648  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>fit7&lt;-lm(Number_of_subjects ~ center_cases*center_controls, data=cancerdata_final)
coeftest(fit7, vcov = vcovHC(fit7))</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##                                Estimate Std. Error    t value Pr(&gt;|t|)    
## (Intercept)                  1.1469e+03 2.0583e-13 5.5720e+15   &lt;2e-16 ***
## center_cases                 1.0000e+00 5.3350e-16 1.8744e+15   &lt;2e-16 ***
## center_controls              1.0000e+00 1.2600e-16 7.9368e+15   &lt;2e-16 ***
## center_cases:center_controls 3.3670e-20 1.4653e-19 2.2980e-01   0.8183    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>#Interpretation: the results did not change much. For the three regressions that I ran, the coefficients, the std. error, and the p-value stays about the same before and after regression with robust SEs. The p values are highly significant. What I am thinking is that the p-value might have got better through the use of robust SEs, but still highly significant anyway so we cannot see the change in significance? Or could it be because the numeric variables of my dataset is just…weird?</p>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code># repeat 5000 times, saving the coefficients each time
samp_distn&lt;-replicate(5000, {
boot_dat&lt;-boot_dat&lt;-cancerdata_final[sample(nrow(cancerdata_final),replace=TRUE),]
fit9&lt;-lm(Number_of_subjects ~ center_cases*center_controls, data=boot_dat)
coef(fit9)
})

## Estimated SEs
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) center_cases center_controls center_cases:center_controls
## 1 7.72559e-13 3.839855e-15    1.962817e-15                 1.248712e-19</code></pre>
<p>#ANSWER: Interpretation: The SEs now are remarkably lowered in comparison to the original SEs and the robust SEs. Bootstrapped SE sounds like a better choice for my dataset because I violated the 2 assumptions (both homoskedasticity and normality )</p>
<ul>
<li><p><strong>5. (30 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (5)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</li>
<li>Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (5)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</li>
</ul></li>
</ul>
<pre class="r"><code># predict $y$ (analytical_methodm LC-MS/MS or HPLC) from `Biospecimen` using a logistic regression

fit_log&lt;-glm(y~Biospecimen, data=cancerdata_final, family=&quot;binomial&quot;)
summary(fit_log)</code></pre>
<pre><code>## 
## Call:
## glm(formula = y ~ Biospecimen, family = &quot;binomial&quot;, data = cancerdata_final)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.2116  -0.5931  -0.3036  -0.2330   2.6907  
## 
## Coefficients:
##                                             Estimate Std. Error z value
## (Intercept)                                  -1.3863     0.7906  -1.754
## BiospecimenPlasma, fasting and non-fasting   -0.2624     0.8153  -0.322
## BiospecimenPlasma, non-fasting              -17.1798  2062.6396  -0.008
## BiospecimenPlasma, unspecified              -17.1798  1006.4653  -0.017
## BiospecimenSerum or Plasma                   -1.0561     1.0810  -0.977
## BiospecimenSerum, fasting                     1.4604     0.8794   1.661
## BiospecimenSerum, fasting and non-fasting    -2.2064     0.9836  -2.243
## BiospecimenSerum, non-fasting                -1.6677     0.9135  -1.826
## BiospecimenSerum, unspecified                -1.0415     0.9939  -1.048
## BiospecimenUrine, overnight                  19.9524  3261.3194   0.006
## BiospecimenUrine, spot                        1.4663     0.8861   1.655
##                                            Pr(&gt;|z|)  
## (Intercept)                                  0.0795 .
## BiospecimenPlasma, fasting and non-fasting   0.7476  
## BiospecimenPlasma, non-fasting               0.9934  
## BiospecimenPlasma, unspecified               0.9864  
## BiospecimenSerum or Plasma                   0.3286  
## BiospecimenSerum, fasting                    0.0968 .
## BiospecimenSerum, fasting and non-fasting    0.0249 *
## BiospecimenSerum, non-fasting                0.0679 .
## BiospecimenSerum, unspecified                0.2947  
## BiospecimenUrine, overnight                  0.9951  
## BiospecimenUrine, spot                       0.0980 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 452.99  on 588  degrees of freedom
## Residual deviance: 349.54  on 578  degrees of freedom
## AIC: 371.54
## 
## Number of Fisher Scoring iterations: 17</code></pre>
<pre class="r"><code>exp(coef(fit_log))%&gt;%round(3)%&gt;%data.frame</code></pre>
<pre><code>##                                                       .
## (Intercept)                                2.500000e-01
## BiospecimenPlasma, fasting and non-fasting 7.690000e-01
## BiospecimenPlasma, non-fasting             0.000000e+00
## BiospecimenPlasma, unspecified             0.000000e+00
## BiospecimenSerum or Plasma                 3.480000e-01
## BiospecimenSerum, fasting                  4.308000e+00
## BiospecimenSerum, fasting and non-fasting  1.100000e-01
## BiospecimenSerum, non-fasting              1.890000e-01
## BiospecimenSerum, unspecified              3.530000e-01
## BiospecimenUrine, overnight                4.625952e+08
## BiospecimenUrine, spot                     4.333000e+00</code></pre>
<p>#ANSWER: The reference category here is plasma, fasting biospecimens. The odds of using HPLC for most of the biospecimens are lower than that of plasma, fasting biospecimens. This is the case, with the exception of those urine specimen, both urine, spot and urine, overnight. The odds of using HPLC for urine, overnight is 462595172.716 times that of plasma, fasting (is this number…also “odd”?). The odd of using HPLC for urine, spot is 4.333 times that of plasma, fasting.</p>
<p>#Report a confusion matrix for your logistic regression (5)</p>
<pre class="r"><code>cancerdata_final&lt;-cancerdata%&gt;%mutate(y=ifelse(analytical_method==&quot;LC-MS/MS&quot;,1,0))
probs&lt;-predict(fit_log,type=&quot;response&quot;)
table(predict=as.numeric(probs&gt;.5),truth=cancerdata_final$analytical_method)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict HPLC LC-MS/MS Sum
##     0    488       45 533
##     1     25       31  56
##     Sum  513       76 589</code></pre>
<pre class="r"><code>#</code></pre>
<p>#ANSWER: Not sure why the confusion matrix doesn not show LC-MS/MS as 1 and HPLC as 0</p>
<p>#Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</p>
<pre class="r"><code>library(plotROC)
#Accuracy:
(488+31)/589</code></pre>
<pre><code>## [1] 0.8811545</code></pre>
<pre class="r"><code>#Sensitivity (TPR): probability of LC-MS/MS if it is actually used for the biospecimen
31/76</code></pre>
<pre><code>## [1] 0.4078947</code></pre>
<pre class="r"><code>#Specificity (TNR): probability of using HPLC if it is actually used
488/513</code></pre>
<pre><code>## [1] 0.9512671</code></pre>
<pre class="r"><code>#Precision (PPV): the proportion of  HPLC usage that is actually used for the biospecimens
31/56</code></pre>
<pre><code>## [1] 0.5535714</code></pre>
<pre class="r"><code>cancerdata_final&lt;-cancerdata_final%&gt;%mutate(probs&lt;-predict(fit_log,type=&quot;response&quot;), prediction=ifelse(probs&gt;.5,1,0))
classify&lt;-cancerdata_final%&gt;%transmute(probs,prediction,truth=y)
classify</code></pre>
<pre><code>## # A tibble: 589 x 3
##     probs prediction truth
##     &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
##  1 0.0450          0     1
##  2 0.161           0     1
##  3 0.161           0     1
##  4 0.0268          0     1
##  5 0.0268          0     1
##  6 0.161           0     1
##  7 0.161           0     1
##  8 0.161           0     1
##  9 0.0450          0     1
## 10 0.161           0     1
## # … with 579 more rows</code></pre>
<pre class="r"><code>ROCplot&lt;-ggplot(classify)+geom_roc(aes(d=truth,m=probs), n.cuts=0)


calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.8069534</code></pre>
<p>#ANSWER: AUC of the model is 0.81, which is a good AUC by the rule of thumb for AUC. The true negative rate is great!</p>
<p>#Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (5)</p>
<pre class="r"><code>## Density plot of log-odds for each outcome:
cancerdata_final&lt;-cancerdata%&gt;%mutate(y=ifelse(analytical_method==&quot;LC-MS/MS&quot;,1,0))

density_plot&lt;-cancerdata_final%&gt;%mutate(y=ifelse(analytical_method==&quot;LC-MS/MS&quot;,1,0))
density_plot$analytical_method&lt;-factor(density_plot$analytical_method,levels=c(&quot;LC-MS/MS&quot;,&quot;HPLC&quot;)) 
head(density_plot)</code></pre>
<pre><code>## # A tibble: 6 x 16
##      ID ExcretionID Subjectgroup Population Country Cohort Number_of_subje…
##   &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt;             &lt;dbl&gt;
## 1   732       21706 All          Hepatocel… China   SCS (…              928
## 2   733       21707 All          Breast ca… United… MEC (…             1412
## 3   734       21708 All          Pancreati… United… EPIC …              927
## 4   737       21711 All          Lung canc… France  EPIC …             2669
## 5   738       21712 All          Lung canc… France  EPIC …             2669
## 6   742       21716 All          Gastric c… Norway  EPIC …              836
## # … with 9 more variables: Number_of_cases &lt;dbl&gt;, Numberofcontrols &lt;dbl&gt;,
## #   Biospecimen &lt;chr&gt;, analytical_method &lt;fct&gt;, Biomarker &lt;chr&gt;, Cancer &lt;chr&gt;,
## #   Study_design &lt;chr&gt;, Publication &lt;chr&gt;, y &lt;dbl&gt;</code></pre>
<pre class="r"><code>fit_plot&lt;-glm(y~Biospecimen, data=density_plot, family=&quot;binomial&quot;)

density_plot$logit&lt;-predict(fit_plot,type=&quot;link&quot;) #get log-odds for everyone

density_plot%&gt;%ggplot()+geom_density(aes(logit,color=analytical_method,fill=analytical_method), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)+
  geom_rug(aes(logit,color=analytical_method))+
  geom_text(x=-6,y=.15,label=&quot;TN = 488&quot;)+
  geom_text(x=-1.75,y=.05,label=&quot;FN = 45&quot;)+
  geom_text(x=-0.5,y=.03,label=&quot;FP = 25&quot;)+
  geom_text(x=2,y=.1,label=&quot;TP = 31&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>#Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</p>
<pre class="r"><code>cancerdata_final&lt;-cancerdata_final%&gt;%mutate(probs&lt;-predict(fit_log,type=&quot;response&quot;), prediction=ifelse(probs&gt;.5,1,0))
classify&lt;-cancerdata_final%&gt;%transmute(probs,prediction,truth=y)
classify</code></pre>
<pre><code>## # A tibble: 589 x 3
##     probs prediction truth
##     &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
##  1 0.0450          0     1
##  2 0.161           0     1
##  3 0.161           0     1
##  4 0.0268          0     1
##  5 0.0268          0     1
##  6 0.161           0     1
##  7 0.161           0     1
##  8 0.161           0     1
##  9 0.0450          0     1
## 10 0.161           0     1
## # … with 579 more rows</code></pre>
<pre class="r"><code>ROCplot&lt;-ggplot(classify)+geom_roc(aes(d=truth,m=probs), n.cuts=0)

ROCplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.8069534</code></pre>
<pre class="r"><code>#AUC: 0.81</code></pre>
<ul>
<li><p><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</p>
<ul>
<li>Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)</li>
<li>Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. (5)</li>
<li>Perform 10-fold CV using only the variables lasso selected: compare model’s out-of-sample AUC to that of your logistic regressions above (5)</li>
</ul></li>
</ul>
<pre class="r"><code>cancer8&lt;-cancerdata_final%&gt;%select(-ID, -ExcretionID,-Subjectgroup)
cancer8_final&lt;-cancer8%&gt;%mutate(y=ifelse(analytical_method==&quot;LC-MS/MS&quot;,1,0))</code></pre>
</div>
<div id="fit-model-compute-in-sample-classification-diagnostics-accuracy-sensitivity-specificity-precision-auc-and-interpret-5" class="section level1">
<h1>Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)</h1>
<pre class="r"><code>#LEAVE THIS CHUNK ALONE!
library(knitr)
opts_chunk$set(fig.align=&quot;center&quot;, fig.height=5, message=FALSE, warning=FALSE, fig.width=8, tidy.opts=list(width.cutoff=60),tidy=TRUE)

class_diag&lt;-function(probs,truth){
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}</code></pre>
<pre class="r"><code>fit10 &lt;- glm(y ~ (.), data = cancer8_final, family = &quot;binomial&quot;)
prob10 &lt;- predict(fit10, type = &quot;response&quot;)
class_diag(prob10, cancer8_final$analytical_method)</code></pre>
<pre><code>##          acc sens spec ppv auc
## LC-MS/MS   1    1    1   1  NA</code></pre>
<p>#ANSWER: So I tried every possible way that I could think of (omitting variable such as ID, excretion ID, subjectgroup). I also tried making a dataset that has randomcombination of variables (not all available variable in the original dataset), and use the newly made dataset to run the logistic regression of analytical method with all the remaining variables. All results came out as being 1. with the AUC is NA. When I tried running y with only one variable, such as Country or Biospecimen, the class_diag results came out normal with reasonable numbers. I guess my data is overfitted?</p>
<p>#- Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)</p>
<pre class="r"><code># THANK YOU DR.WOODWARD SO MUCH FOR HELPING ME SOLVING THIS
# PROBLEM. I KNOW THAT I MADE A BAD CHOICE OF CHOOSING THE
# DATASET BUT YOU SAVED IT!
set.seed(1234)
k = 10

# A lot of variables in this dataset has one single
# observation for a category. So I filtered them out before
# regressing.
cancer9_final &lt;- cancerdata_final %&gt;% mutate(y = ifelse(analytical_method == 
    &quot;LC-MS/MS&quot;, 1, 0))

tidycancer &lt;- cancer9_final %&gt;% select(-ID, -ExcretionID, -Subjectgroup, 
    -Biomarker, -Publication, -Study_design, -analytical_method) %&gt;% 
    group_by(Cohort) %&gt;% filter(n() &gt; 10)

tidycancer2 &lt;- tidycancer %&gt;% group_by(Population) %&gt;% filter(n() &gt; 
    4)
tidycancer2 &lt;- tidycancer2 %&gt;% ungroup %&gt;% na.omit()

# Until Here. Done filtering. Time for 10-fold cross
# validation
data11 &lt;- tidycancer2[sample(nrow(tidycancer2)), ]  #put dataset in random order
folds &lt;- cut(seq(1:nrow(tidycancer2)), breaks = k, labels = F)  #create folds

diags &lt;- NULL
for (i in 1:k) {
    # FOR EACH OF 10 FOLDS
    train &lt;- data11[folds != i, ]  # CREATE TRAINING SET
    test &lt;- data11[folds == i, ]  # CREATE TESTING SET
    
    truth2 &lt;- test$y
    
    fit11 &lt;- glm(y ~ (.), data = train, family = &quot;binomial&quot;)
    prob11 &lt;- predict(fit11, newdata = test, type = &quot;response&quot;)
    summary(fit11)
    diags &lt;- rbind(diags, class_diag(prob11, truth2))  #CV DIAGNOSTICS FOR EACH FOLD
}

summarize_all(diags, mean)  #AVERAGE THE DIAGNOSTICS ACROSS THE 10 FOLDS</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.9710101 0.8788095 0.9899294 0.9371429 0.9343695</code></pre>
<p>#ANSWER: the ACC is 0.95, the sensitivity is 0.87, the specificity is 0.99, the ppv is 0.90, the AUC is 0.93, which is great. I can’t compare to the in-sample metrics, because the model in the previous step was actually overfitted. Anyway, the AUC in both models are great.</p>
<p>#Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. (5)</p>
<pre class="r"><code># install.packages(&#39;glmnet&#39;)
library(glmnet)
set.seed(1234)
# your code here
cancer9_final &lt;- cancerdata_final %&gt;% mutate(y = ifelse(analytical_method == 
    &quot;LC-MS/MS&quot;, 1, 0))
tidycancer &lt;- cancer9_final %&gt;% select(-ID, -ExcretionID, -Subjectgroup, 
    -Biomarker, -Publication, -Study_design, -analytical_method) %&gt;% 
    group_by(Cohort) %&gt;% filter(n() &gt; 10)

tidycancer2 &lt;- tidycancer %&gt;% group_by(Population) %&gt;% filter(n() &gt; 
    4)
tidycancer2 &lt;- tidycancer2 %&gt;% ungroup %&gt;% na.omit()

y &lt;- as.matrix(tidycancer2$y)  #grab response
x &lt;- model.matrix(y ~ ., data = tidycancer2)[, -1]  #grab predictors

cv &lt;- cv.glmnet(x, y, family = &quot;binomial&quot;)  #picks an optimal value for lambda through 10-fold CV

{
    plot(cv$glmnet.fit, &quot;lambda&quot;, label = TRUE)
    abline(v = log(cv$lambda.1se))
    abline(v = log(cv$lambda.min), lty = 2)
}</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-29-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>cv &lt;- cv.glmnet(x, y, family = &quot;binomial&quot;)
lasso &lt;- glmnet(x, y, family = &quot;binomial&quot;, lambda = cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 62 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                                                                                           s0
## (Intercept)                                                                                                .
## PopulationBrain cancer cases and their controls                                                            0
## PopulationBreast cancer cases and their controls                                                           .
## PopulationCervical cancer cases and their controls                                                         .
## PopulationColorectal cancer cases and their controls                                                       .
## PopulationGastric adenocarcinoma cases and their controls                                                  .
## PopulationGastric cancer cases and their controls                                                          .
## PopulationHepatocellular carcinoma cases and their controls                                                .
## PopulationLung cancer cases and their controls                                                             .
## PopulationNon-Hodgkin lymphoma cases and their controls                                                    .
## PopulationOral and pharyngeal cancer cases and their controls                                              .
## PopulationOvarian cancer cases and their controls                                                          .
## PopulationPancreatic cancer cases and their controls                                                       .
## PopulationPostmenopausal breast cancer cases and their controls                                            .
## PopulationProstate cancer cases and their controls                                                         .
## PopulationUpper aerodigestive tract cancer cases and their controls                                        .
## PopulationUrothelial cancer cases and their controls                                                       .
## PopulationUrothelial cell carcinoma cases and their controls                                               .
## CountryFinland                                                                                             .
## CountryFrance                                                                                              .
## CountryJapan                                                                                               .
## CountryNetherlands                                                                                         .
## CountryNorway                                                                                              .
## CountryUnited Kingdom                                                                                      .
## CountryUnited States                                                                                       .
## CohortCLUE                                                                                                 .
## CohortCombined cohorts                                                                                     .
## CohortE3N (Etude Epidemiologique aupres des femmes de la Mutuelle Generale de l\x83??Education Nationale)  .
## CohortEPIC (European Prospective Investigation into Cancer and Nutrition)                                  .
## CohortHHP (Honolulu Heart Program)                                                                         .
## CohortJACC Study (Japan Collaborative Cohort Study)                                                        .
## CohortJPHC (Japan Public Health Center-based Prospective Study on Cancer and Cardiovascular Diseases)      .
## CohortMEC (Multiethnic Cohort Study)                                                                       .
## CohortNHS (Nurses&#39; Health Study)                                                                           .
## CohortSCS (Shanghai Cohort Study)                                                                          .
## CohortSWHS (Shanghai Women&#39;s Health Study)                                                                 .
## Number_of_subjects                                                                                         .
## Number_of_cases                                                                                            .
## Numberofcontrols                                                                                           .
## BiospecimenPlasma, fasting and non-fasting                                                                 .
## BiospecimenPlasma, unspecified                                                                             .
## BiospecimenSerum or Plasma                                                                                 .
## BiospecimenSerum, fasting                                                                                  .
## BiospecimenSerum, fasting and non-fasting                                                                  .
## BiospecimenSerum, non-fasting                                                                              .
## BiospecimenSerum, unspecified                                                                              .
## BiospecimenUrine, overnight                                                                                .
## BiospecimenUrine, spot                                                                                     .
## CancerBrain cancer                                                                                         .
## CancerBreast cancer                                                                                        .
## CancerCervical cancer                                                                                      .
## CancerColon and rectal cancer                                                                              .
## CancerGastric and oesophageal cancer                                                                       .
## CancerHead and neck cancer                                                                                 .
## CancerLiver cancer                                                                                         .
## CancerLung cancer                                                                                          .
## CancerLymphoid cancer                                                                                      .
## CancerOvarian cancer                                                                                       .
## CancerPancreatic cancer                                                                                    .
## CancerProstate cancer                                                                                      .
## `probs &lt;- predict(fit_log, type = &quot;response&quot;)`                                                             .
## prediction                                                                                                 .</code></pre>
<p>#ANSWER: Hmmmmm…weird. The only value retaining is Brain cancer cases and their controls, with a 0 coefficient… I will just use that one value for the LASSO</p>
<pre class="r"><code># classification diagnostics
lasso_dat1 &lt;- tidycancer2 %&gt;% mutate(Braincancer = ifelse(Population == 
    &quot;Brain cancer cases and their controls&quot;, 1, 0)) %&gt;% select(Braincancer, 
    y)

lasso_dat &lt;- glm(y ~ Braincancer, data = lasso_dat1, family = &quot;binomial&quot;)
summary(lasso_dat)</code></pre>
<pre><code>## 
## Call:
## glm(formula = y ~ Braincancer, family = &quot;binomial&quot;, data = lasso_dat1)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.4942  -0.4942  -0.4942  -0.4942   2.0801  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -2.0412     0.1503 -13.579   &lt;2e-16 ***
## Braincancer  18.6073   641.3053   0.029    0.977    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 367.77  on 448  degrees of freedom
## Residual deviance: 310.35  on 447  degrees of freedom
## AIC: 314.35
## 
## Number of Fisher Scoring iterations: 15</code></pre>
<pre class="r"><code>prob_lasso &lt;- predict(lasso_dat, type = &quot;response&quot;)
class_diag(prob_lasso, lasso_dat1$y)</code></pre>
<pre><code>##         acc    sens spec ppv      auc
## 1 0.8886414 0.21875    1   1 0.609375</code></pre>
<p>#ANSWER: Using the LASSO-selected model, the AUC drops remarkably, bad AUC at 0.609</p>
<p>#Perform 10-fold CV using only the variables lasso selected: compare model’s out-of-sample AUC to that of your logistic regressions above (5)</p>
<pre class="r"><code>set.seed(1234)
k = 10


data_lasso &lt;- lasso_dat1[sample(nrow(lasso_dat1)), ]  #put dataset in random order
folds_lasso &lt;- cut(seq(1:nrow(lasso_dat1)), breaks = k, labels = F)  #create folds

diags_lasso &lt;- NULL
for (i in 1:k) {
    # FOR EACH OF 10 FOLDS
    train_lasso &lt;- data_lasso[folds_lasso != i, ]  # CREATE TRAINING SET
    test_lasso &lt;- data_lasso[folds_lasso == i, ]  # CREATE TESTING SET
    
    truth_lasso &lt;- test_lasso$y
    
    fit_lasso &lt;- glm(y ~ (.), data = train_lasso, family = &quot;binomial&quot;)
    prob_lasso_10cv &lt;- predict(fit_lasso, newdata = test_lasso, 
        type = &quot;response&quot;)
    summary(fit_lasso)
    diags_lasso &lt;- rbind(diags_lasso, class_diag(prob_lasso_10cv, 
        truth_lasso))  #CV DIAGNOSTICS FOR EACH FOLD
}

summarize_all(diags_lasso, mean)  #AVERAGE THE DIAGNOSTICS ACROSS THE 10 FOLDS</code></pre>
<pre><code>##         acc      sens spec ppv       auc
## 1 0.8886364 0.2221429    1 NaN 0.6110714</code></pre>
<p>#ANSWER: The out-of-sample AUC and the AUC from the lasso-selected model above are very similar, around 0.611. Still bad~</p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
